### ISSUE TITLE
presets buttons only work on first DateRangePicker in v-for loop

### ISSUE THREAD

**Issue by About7Sharks** [damienroche/vue-mj-daterangepicker#11]
```
<div v-for="(Device,key) in Devices" :key="key">
<date-range-picker :ref="Device.Id"  @update="update" :theme="dateRangeTheme"  :from="Device.startDate" :to="Device.endDate" :presets='presets' :panels="['range', 'week', 'month']"/>
</div>
```

Only the first iteration of the date-range-picker component allows me to change the presets. The others don't respond when I click the input button. Although the Submit and Reset ranges buttons work still. I'm not receiving any errors in my console.

**Comment by damienroche** [comment]
can you provide a link to reproduce this behavior ?

the following example seems to work :
[https://codesandbox.io/s/vue-template-nhpv6?fontsize=14](url)

**Comment by About7Sharks** [comment]
So after playing around with it a little more it seems to only allow me to switch the presets when there's one open. If I open all of them only the first will be active then if i close the first the second starts to work and so on. I can either hide the date-range-picker component when the user slides to the next page but thats less than ideal.

**Comment by Horsetoast** [comment]
@damienroche I've encountered the same problem and was able to reproduce here:
https://codesandbox.io/s/suspicious-jepsen-lz1yp?fontsize=14&hidenavigation=1&theme=dark

Try selecting a preset in the second datepicker, it will select the preset in the first datepicker instead.

**Comment by damienroche** [comment]
@Horsetoast thanks for the PR. this will be available on the next release
