### ISSUE TITLE
Is there a option to show 6 weeks in range panel when first day of month is Sunday

### ISSUE THREAD

**Issue by CGTDev92** [damienroche/vue-mj-daterangepicker#21]
As plugin show only 5 weeks in panel therefor if first day of month is last day of week of previous month then it will not appear in current calendar month. Like in attach image 1st March 2020 is not shown in March 2020 calendar.
![firstMarchNotAvailable](https://user-images.githubusercontent.com/12963661/75663228-7c640180-5c96-11ea-812c-ca2aca70ef5d.png)

**Comment by CGTDev92** [comment]
Can you please add below condition in "updateCalendar()" function at line 13200 within File "vue-mj-daterangepicker.common.js". This will resolve this issue of not showing first day of month when it is Sunday.

if(nbDaysLastMonth == -1) {
    nbDaysLastMonth = 6;
}

**Comment by damienroche** [comment]
@CGTDev92 thanks for report this. I'll fix this asap.

**Comment by CGTDev92** [comment]
> @CGTDev92 thanks for report this. I'll fix this asap.

Any update on this ?

**Comment by damienroche** [comment]
I just fixed it, i will upload an new version today

**Comment by damienroche** [comment]
fixed in v0.1.11
