### ISSUE TITLE
other locales

### ISSUE THREAD

**Issue by ONiAd** [damienroche/vue-mj-daterangepicker#6]
Is possible to add other locales like 'es'?

Thanks

**Comment by damienroche** [comment]
Hello,

You can make a pull request by adding a es key in /src/translations/index.js
or you can translate here the following keys in the `es` object and I will update the library

`
en: {
    reset: 'Reset ranges',
    submit: 'Submit',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    previousYear: 'Previous year',
    nextYear: 'Next year',
    quarter: 'Quarter',
    panels: {
      range: 'Range',
      week: 'Week',
      month: 'Month',
      quarter: 'Quarter',
      year: 'Year'
    },
    presets: {
      custom: 'Custom range',
      forever: 'From the beginning',
      last7days: 'Last 7 days',
      last30days: 'Last 30 days',
      last90days: 'Last 90 days',
      last365days: 'Last 365 days',
      next365days: 'next 365 days',
      next90days: 'Next 90 days',
      next30days: 'Next 30 days',
      next7days: 'Next 7 days',
      today: 'Today',
      tomorrow: 'Tomorrow',
      yesterday: 'Yesterday'
    }
  },
es: {
    reset: 'Reset ranges',
    submit: 'Submit',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    previousYear: 'Previous year',
    nextYear: 'Next year',
    quarter: 'Quarter',
    panels: {
      range: 'Range',
      week: 'Week',
      month: 'Month',
      quarter: 'Quarter',
      year: 'Year'
    },
    presets: {
      custom: 'Custom range',
      forever: 'From the beginning',
      last7days: 'Last 7 days',
      last30days: 'Last 30 days',
      last90days: 'Last 90 days',
      last365days: 'Last 365 days',
      next365days: 'next 365 days',
      next90days: 'Next 90 days',
      next30days: 'Next 30 days',
      next7days: 'Next 7 days',
      today: 'Today',
      tomorrow: 'Tomorrow',
      yesterday: 'Yesterday'
    }
  }
`

`
es: {
    reset: '',
    submit: '',
    previousMonth: '',
    nextMonth: '',
    previousYear: '',
    nextYear: '',
    quarter: '',
    panels: {
      range: '',
      week: '',
      month: '',
      quarter: '',
      year: '',
    },
    presets: {
      custom: '',
      forever: '',
      last7days: '',
      last30days: '',
      last90days: '',
      last365days: '',
      next365days: '',
      next90days: '',
      next30days: '',
      next7days: '',
      today: '',
      tomorrow: '',
      yesterday: '',
    }
  }
`

**Comment by damienroche** [comment]
ok I just see your pull request

**Comment by damienroche** [comment]
german and spanish translations are now available in version 0.1.6

**Comment by pedrotcm** [comment]
How to translate months and days names?

**Comment by damienroche** [comment]
@pedrotcm not sure I understand about what you mean. Can you be more specific ?
